# Generated by Django 5.0.6 on 2024-06-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('chapters_count', models.IntegerField(default=0)),
                ('read', models.CharField(default='0', max_length=10000)),
                ('title', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('lending_gender', models.CharField(max_length=30)),
                ('views', models.IntegerField(default=0)),
                ('chapters', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('age_range', models.IntegerField(default=5)),
                ('tags', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='catalog/books/coverimages/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=20000000)),
                ('un_save_text', models.CharField(max_length=1000000)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField(default=0)),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('hours_spent', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('novels', models.ManyToManyField(through='novel.ReadingActivity', to='novel.novel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readingactivity',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.shelf'),
        ),
    ]
