# Generated by Django 5.0.6 on 2024-06-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_rename_lending_gender_novel_leading_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(upload_to='cover/'),
        ),
    ]
