# Generated by Django 5.0.6 on 2024-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_alter_novel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='chapters',
        ),
        migrations.AddField(
            model_name='novel',
            name='chapters',
            field=models.ManyToManyField(to='novel.chapter'),
        ),
    ]
