# Generated by Django 5.0.6 on 2024-07-30 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_remove_chapter_novel_remove_novel_chapters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapters',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(max_length=20000000),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='un_save_text',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='novel',
            name='chapters',
            field=models.ManyToManyField(related_name='chapters_table', to='novel.chapter'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='read',
            field=models.CharField(default=0, max_length=10000),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('chapter',)},
        ),
        migrations.CreateModel(
            name='UsersReder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='users_reades',
            field=models.ManyToManyField(related_name='read_users', to='novel.usersreder'),
        ),
    ]
