# Generated by Django 5.0.6 on 2024-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(max_length=20000000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='un_save_text',
            field=models.TextField(max_length=1000000, null=True),
        ),
    ]
