# Generated by Django 5.0.6 on 2024-08-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_rename_un_save_text_chapter_unsave_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='unsave_text',
            new_name='unsaved_text',
        ),
    ]
