# Generated by Django 5.0.6 on 2024-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_rename_unsave_text_chapter_unsaved_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
