# Generated by Django 5.0.6 on 2024-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
